### ISSUE TITLE
BeerJS #7: Jawsspot

### ISSUE THREAD

**Issue by sashasushko** [beerjs/spb#5]
Date: 14 August 2019
Place: https://yandex.ru/maps/-/CGRr5NKe (Mayakovskogo str., 11)
Time: 7 PM

If you come, let us know by commenting the issue.

---

Везу привет от [beerjs/ekb](https://github.com/beerjs/ekb)

**Comment by jkikksa** [comment]
В это время будет PiterJS

**Comment by sashasushko** [comment]
@jkikksa он не 16 августа?

**Comment by jkikksa** [comment]
сорян, попутался

**Comment by sashasushko** [comment]
@jkikksa придешь тогда?

**Comment by sashasushko** [comment]
:-(
